### PR TITLE
Fix modal overflow

### LINKED ISSUE #138: [BUG] Modal overflow hidden
## Describe the bug
If a modal's height is taller than the viewport's height, there is no scrolling allowed. Current workaround is to zoom out on the page so that the entire modal can be seen.

## Steps to reproduce
1. Go to admin.nwplus.io
2. Click on Livesite -> Judging -> open a modal
3. If your screen isn't tall enough, the entire modal can't be seen

## Expected behavior
Should be able to scroll and view entire contents of modal

## Screenshots/Videos
image

### PR DESCRIPTION
**Pull request by kevin-zou**
## Description
Closes #138. Set max-height to 75% and added overflow support to fix the bug.

Also just added some padding to the button container since it was hugging the bottom edge before.

Before (unscrollable):
image

After:
image

### CODE REVIEW

File: components/modal.js [hunk 1]
```diff
@@ -137,11 +137,13 @@ const ModalBackground = styled.div`
   /* TODO: add media queries to make width responsive */
   width: 740px;
   max-width: 100%;
-  max-height: 100%;
+  max-height: 70%;
+  overflow: scroll;
```
Comment (naijwu) [inline components/modal.js:141]: Super small thing: `overflow: scroll;` shows the scroll bar containers for both horizontal and vertical scroll even when there isn't overflow -- this isn't obvious on Apple devices (everything looks better on Apple devices?) but on Windows the scrollbars are kinda chunky. 

Horizontal overflow shouldn't exist so this line could be `overflow-x: auto;`, which would only show vertical scroll when overflow exists

**Review by naijwu — APPROVED** [review]

File: components/modal.js (hunk 1 above)
Comment (kevin-zou) [reply components/modal.js]: OH great call, added in a306420
